### ISSUE TITLE
Release package.json doesn't contain "main" section

### ISSUE THREAD

**Issue by LoranRendel** [edwinm/Shadow-animation-jQuery-plugin#3]
There is no main section in release when install using npm or yarn.

**Comment by edwinm** [comment]
Ik see this on line 8 of package.json:
`"main": "jquery.animate-shadow-min.js",`

What exactly do you mean?

**Comment by LoranRendel** [comment]
It's in dev-master, not in release, yarn/npm installs latest release by default.
Try `npm install jquery-shadow-animation`

**Comment by LoranRendel** [comment]
Another note: minified files usually `.min.js` but not `-min.js`

**Comment by edwinm** [comment]
Ah, seems latest version in GitHub was not published to npm. This is fixed now, please try again.

I won't fix the `min` postfix, as this will break current websites.

**Comment by LoranRendel** [comment]
Yes, all ok
